export const settingsGetResponses: Record<string, unknown> = {
  "/api/user/config": {
    force_sync_external: false,
    match_rule: "node_name",
    sync_scope: "saved_only",
    keep_node_name: true,
    cache_expire_minutes: 0,
    sync_traffic: true,
    node_name_filter: "剩余|流量|到期|订阅|时间|重置",
    append_sub_info: false,
    custom_rules_enabled: true,
    enable_short_link: true,
    use_new_template_system: true,
    enable_proxy_provider: false,
    node_order: [1, 2, 3, 4, 5, 6, 7],
    proxy_groups_source_url: "",
    client_compatibility_mode: false,
  },
  "/api/admin/system-settings/master-url": { master_url: "https://arcway.example.com" },
  "/api/admin/system-settings/default-theme": { default_theme: "flat" },
  "/api/admin/system-settings/login-wallpaper": { login_wallpaper: "" },
  "/api/admin/system-settings/intervals": {
    speed_collect_interval: 3,
    traffic_collect_interval: 60,
    traffic_check_interval: 120,
    heartbeat_interval: 30,
    report_interval: 5,
  },
  "/api/admin/system-settings/probe-disguise": {
    enabled: true,
    title: "Arcway Status",
    server_ids: [1],
    show_name: true,
  },
  "/api/admin/system-settings/short-link": { enable_short_link: true },
  "/api/admin/system-settings/node-name-multiplier-prefix": { enabled: true, left: "[", right: "]" },
  "/api/admin/system-settings/override-scripts": { enable_override_scripts: false },
  "/api/admin/system-settings/subscription-output-format": { subscription_output_format: "yaml" },
  "/api/admin/system-settings/silent-mode": { silent_mode: false, silent_mode_timeout: 15 },
  "/api/admin/system-settings/miaomiaowu-features": { enable_miaomiaowu_features: true },
  "/api/admin/system-settings/mmw-short-link-compat": { enable_mmw_short_link_compat: false },
  "/api/admin/system-settings/agent-log": { agent_log_enabled: false },
  "/api/admin/rule-templates": { templates: ["balanced_v3.yaml"], owners: { "balanced_v3.yaml": "admin" } },
  "/api/admin/system-settings/default-template": { default_template_filename: "balanced_v3.yaml" },
  "/api/admin/system-settings/redeem-template": {
    redeem_template: "使用教程\n打开机器人 {机器人地址}\n发送兑换码 {兑换码}\n等待机器人确认\n返回主控 {主控域名}\n复制订阅地址",
  },
  "/api/admin/security-settings": {
    login_rate_max_attempts: 5,
    login_rate_window_minutes: 60,
    login_rate_lock_minutes: 60,
    brute_force_enabled: true,
    brute_force_max_failures: 5,
    brute_force_window_minutes: 1440,
    brute_force_block_minutes: 1440,
    sub_rate_enabled: true,
    sub_rate_limit: 60,
    sub_rate_window_minutes: 1,
    skip_local_ip: true,
    turnstile_site_key: "",
    turnstile_secret_key: "",
  },
  "/api/admin/system-settings/require-encryption": { require_encryption: true },
  "/api/admin/system-settings/user-permissions": {
    config: {
      pages: ["subscription", "generator", "nodes", "templates", "subscribe-files"],
      quota_template: 3,
      quota_override: 3,
      quota_subscribe: 5,
      routed_outbound_enabled: true,
      quota_routed_outbound: 2,
      daily_limit_routed_outbound: 5,
    },
  },
  "/api/admin/notify-config": {
    notify_enabled: false,
    telegram_bot_token: "",
    telegram_chat_id: "",
    notify_login: false,
    notify_subscribe_fetch: false,
    notify_daily_traffic: false,
    notify_server_offline: true,
    notify_server_online: true,
    notify_traffic_threshold: false,
    notify_daily_traffic_time: "09:00",
    notify_traffic_threshold_percent: 90,
    notify_traffic_threshold_80: false,
    notify_over_limit: true,
    notify_package_expiring: true,
    notify_package_expiring_days: 3,
    notify_package_expired: true,
    notify_user_registered: false,
    notify_telegram_bound: false,
    notify_cert_result: true,
    notify_agent_long_offline: true,
    notify_agent_long_offline_minutes: 10,
    notify_device_limit_exceeded: true,
    notify_server_tolerance_seconds: 60,
  },
  "/api/admin/system-settings/api-token": { token: "masked-test-token" },
  "/api/admin/update/check": {
    current_version: "0.5.0",
    latest_version: "0.5.1",
    has_update: true,
    release_url: "https://github.com/violetaini/relaydock/releases/tag/v0.5.1",
    download_url: "https://github.com/violetaini/relaydock/releases/download/v0.5.1/arcway-linux-amd64",
    release_notes: "新增面板一键更新，并强化更新校验与回滚保护。",
    deployment_mode: "standalone",
    update_scope: "full",
    external_web_root: false,
    can_apply: true,
  },
};
